import React, { useState } from 'react';
import { WeeklyReportData, SectionType } from './types';
import { SectionInput } from './components/SectionInput';
import { 
  Trophy, 
  TrendingUp, 
  Target, 
  Download, 
  Calendar, 
  User, 
  CheckCircle2,
  Quote,
  FileText
} from 'lucide-react';

const INITIAL_DATA: WeeklyReportData = {
  name: '',
  dateRange: '',
  successes: ['', '', ''],
  improvements: ['', '', ''],
  commitments: ['', '', ''],
};

const App: React.FC = () => {
  const [data, setData] = useState<WeeklyReportData>(INITIAL_DATA);
  const [isPreviewMode, setIsPreviewMode] = useState(false);

  const handleInputChange = (field: keyof WeeklyReportData, value: string) => {
    setData((prev) => ({ ...prev, [field]: value }));
  };

  const handleListChange = (type: SectionType, index: number, value: string) => {
    setData((prev) => {
      const newList = [...prev[type]];
      newList[index] = value;
      return { ...prev, [type]: newList };
    });
  };

  const handleDownload = () => {
    const content = `BÁO CÁO TUẦN
----------------------------------------
Họ và tên: ${data.name || '...'}
Tuần: ${data.dateRange || '...'}

"In the moment of decision, your destiny is shaped."

1. 03 VIỆC ĐÃ THÀNH CÔNG:
${data.successes.map((item, i) => `   ${i + 1}. ${item || '(Trống)'}`).join('\n')}

2. 03 VIỆC CÓ THỂ LÀM TỐT HƠN:
${data.improvements.map((item, i) => `   ${i + 1}. ${item || '(Trống)'}`).join('\n')}

3. 03 VIỆC CAM KẾT TUẦN SAU:
${data.commitments.map((item, i) => `   ${i + 1}. ${item || '(Trống)'}`).join('\n')}
----------------------------------------
Generated by Weekly Destiny Report
`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Bao_Cao_Tuan_${data.name.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 pb-12">
      {/* Header */}
      <header className="bg-white border-b border-slate-200 sticky top-0 z-50">
        <div className="max-w-5xl mx-auto px-4 py-4 sm:px-6 lg:px-8">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <h1 className="text-2xl font-bold text-slate-900 tracking-tight flex items-center gap-2">
                <FileText className="w-6 h-6 text-brand-600" />
                Weekly Report
              </h1>
              <p className="text-slate-500 text-sm mt-1 font-medium">Build your discipline, shape your future.</p>
            </div>
            
            <div className="flex items-center gap-3">
              <button
                onClick={() => setIsPreviewMode(!isPreviewMode)}
                className="px-4 py-2 text-sm font-medium text-slate-600 bg-slate-100 rounded-lg hover:bg-slate-200 transition-colors"
              >
                {isPreviewMode ? 'Chỉnh sửa' : 'Xem trước'}
              </button>
              <button
                onClick={handleDownload}
                className="flex items-center gap-2 px-5 py-2.5 bg-brand-600 hover:bg-brand-700 text-white text-sm font-semibold rounded-lg shadow-sm shadow-brand-500/30 transition-all active:scale-95"
              >
                <Download className="w-4 h-4" />
                Tải Báo Cáo
              </button>
            </div>
          </div>
        </div>
      </header>

      {/* Quote Banner */}
      <div className="bg-slate-900 text-white py-12 px-4 relative overflow-hidden">
        <div className="absolute top-0 left-0 w-full h-full opacity-10 pointer-events-none">
           <svg width="100%" height="100%">
             <pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse">
               <path d="M 40 0 L 0 0 0 40" fill="none" stroke="white" strokeWidth="1"/>
             </pattern>
             <rect width="100%" height="100%" fill="url(#grid)" />
           </svg>
        </div>
        <div className="max-w-3xl mx-auto text-center relative z-10">
          <Quote className="w-10 h-10 text-brand-500 mx-auto mb-4 opacity-80" />
          <h2 className="font-serif text-3xl md:text-4xl italic leading-relaxed text-slate-100">
            "In the moment of decision, your destiny is shaped."
          </h2>
          <div className="w-24 h-1 bg-brand-500 mx-auto mt-6 rounded-full"></div>
        </div>
      </div>

      <main className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 -mt-8 relative z-20">
        
        {/* Preview Mode */}
        {isPreviewMode ? (
          <div className="bg-white rounded-2xl shadow-xl overflow-hidden animate-fade-in border border-slate-200">
            <div className="p-8 md:p-12">
              <div className="border-b-2 border-slate-100 pb-8 mb-8 flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
                <div>
                   <h2 className="text-3xl font-bold text-slate-900 mb-2">BÁO CÁO TUẦN</h2>
                   <div className="flex flex-col gap-1 text-slate-500">
                      <span className="flex items-center gap-2"><User className="w-4 h-4" /> {data.name || 'Chưa nhập tên'}</span>
                      <span className="flex items-center gap-2"><Calendar className="w-4 h-4" /> {data.dateRange || 'Chưa nhập ngày'}</span>
                   </div>
                </div>
                <div className="text-right hidden md:block">
                  <div className="text-sm font-semibold text-brand-600 uppercase tracking-widest">Destiny Report</div>
                  <div className="text-xs text-slate-400 mt-1">{new Date().toLocaleDateString('vi-VN')}</div>
                </div>
              </div>

              <div className="space-y-10">
                <section>
                  <h3 className="text-lg font-bold text-emerald-700 flex items-center gap-2 mb-4 bg-emerald-50 p-3 rounded-lg inline-flex pr-6">
                    <Trophy className="w-5 h-5" /> 3 Việc Đã Thành Công
                  </h3>
                  <ul className="space-y-3 pl-2">
                    {data.successes.map((item, idx) => (
                      <li key={idx} className="flex items-start gap-3">
                         <div className="mt-1 min-w-[24px] h-6 flex items-center justify-center bg-emerald-100 text-emerald-700 rounded-full text-xs font-bold">{idx + 1}</div>
                         <p className="text-slate-700 leading-relaxed text-lg border-b border-dotted border-slate-200 pb-1 w-full">{item || '...'}</p>
                      </li>
                    ))}
                  </ul>
                </section>

                <section>
                  <h3 className="text-lg font-bold text-amber-700 flex items-center gap-2 mb-4 bg-amber-50 p-3 rounded-lg inline-flex pr-6">
                    <TrendingUp className="w-5 h-5" /> 3 Việc Cần Cải Thiện
                  </h3>
                  <ul className="space-y-3 pl-2">
                    {data.improvements.map((item, idx) => (
                      <li key={idx} className="flex items-start gap-3">
                         <div className="mt-1 min-w-[24px] h-6 flex items-center justify-center bg-amber-100 text-amber-700 rounded-full text-xs font-bold">{idx + 1}</div>
                         <p className="text-slate-700 leading-relaxed text-lg border-b border-dotted border-slate-200 pb-1 w-full">{item || '...'}</p>
                      </li>
                    ))}
                  </ul>
                </section>

                <section>
                  <h3 className="text-lg font-bold text-blue-700 flex items-center gap-2 mb-4 bg-blue-50 p-3 rounded-lg inline-flex pr-6">
                    <Target className="w-5 h-5" /> 3 Cam Kết Tuần Sau
                  </h3>
                  <ul className="space-y-3 pl-2">
                    {data.commitments.map((item, idx) => (
                      <li key={idx} className="flex items-start gap-3">
                         <div className="mt-1 min-w-[24px] h-6 flex items-center justify-center bg-blue-100 text-blue-700 rounded-full text-xs font-bold">{idx + 1}</div>
                         <p className="text-slate-700 leading-relaxed text-lg border-b border-dotted border-slate-200 pb-1 w-full">{item || '...'}</p>
                      </li>
                    ))}
                  </ul>
                </section>
              </div>

              <div className="mt-12 pt-8 border-t border-slate-100 text-center text-slate-400 text-sm italic font-serif">
                "Small disciplines repeated with consistency every day lead to great achievements gained slowly over time."
              </div>
            </div>
          </div>
        ) : (
          /* Editor Mode */
          <div className="grid grid-cols-1 gap-6">
            
            {/* Personal Info Card */}
            <div className="bg-white p-6 md:p-8 rounded-2xl shadow-sm border border-slate-100">
              <div className="flex items-center gap-2 mb-6 text-slate-800">
                <div className="bg-slate-100 p-2 rounded-lg"><User className="w-5 h-5" /></div>
                <h3 className="font-bold text-lg">Thông Tin Cơ Bản</h3>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <label className="block text-sm font-semibold text-slate-700 mb-2">Họ và tên</label>
                  <input
                    type="text"
                    value={data.name}
                    onChange={(e) => handleInputChange('name', e.target.value)}
                    placeholder="Ví dụ: Quang Duy"
                    className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-brand-500 focus:border-transparent outline-none transition-all"
                  />
                </div>
                <div>
                  <label className="block text-sm font-semibold text-slate-700 mb-2">Thời gian (Tuần)</label>
                  <div className="relative">
                    <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400" />
                    <input
                      type="text"
                      value={data.dateRange}
                      onChange={(e) => handleInputChange('dateRange', e.target.value)}
                      placeholder="Ví dụ: 1-7/12/2023"
                      className="w-full pl-10 pr-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-brand-500 focus:border-transparent outline-none transition-all"
                    />
                  </div>
                </div>
              </div>
            </div>

            {/* Input Sections */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <SectionInput
                type="successes"
                title="3 Việc Đã Thành Công"
                subtitle="Celebrate Wins"
                items={data.successes}
                icon={<Trophy className="w-6 h-6 text-emerald-600" />}
                colorClass="bg-emerald-500"
                placeholder={[
                  "VD: Học kinh tế vi mô trong 2 tiếng",
                  "VD: Viết xong bức tranh mục tiêu",
                  "VD: Đọc 30 trang sách triết học"
                ]}
                onChange={handleListChange}
              />

              <SectionInput
                type="improvements"
                title="3 Việc Cần Cải Thiện"
                subtitle="Refine Process"
                items={data.improvements}
                icon={<TrendingUp className="w-6 h-6 text-amber-600" />}
                colorClass="bg-amber-500"
                placeholder={[
                  "VD: Giải 3 đề thống kê ứng dụng",
                  "VD: Chạy 30 phút mỗi ngày",
                  "VD: Ghi âm bài giảng của thầy về nghe lại"
                ]}
                onChange={handleListChange}
              />

              <SectionInput
                type="commitments"
                title="3 Cam Kết Tuần Sau"
                subtitle="Shape Destiny"
                items={data.commitments}
                icon={<Target className="w-6 h-6 text-blue-600" />}
                colorClass="bg-blue-500"
                placeholder={[
                  "VD: Đi đánh pickleball cùng LM CLB TTVS",
                  "VD: Làm thuyết trình về kinh tế vĩ mô với anh Trường",
                  "VD: Chạy 5km"
                ]}
                onChange={handleListChange}
              />
            </div>
          </div>
        )}
      </main>
    </div>
  );
};

export default App;